### ISSUE TITLE
How to add a testInstallation function?

### ISSUE THREAD

**Issue by lvotapka** [openmm/openmmexampleplugin#30]
Hi Peter. As you know, OpenMM has such a convenient call to run some quick tests after installation:

```
python -m openmm.testInstallation
```

How would be the best way to craft and run such tests in this example plugin?

Example:
```
python -m openmmexampleplugin.testInstallation
```

**Comment by peastman** [comment]
Here's the regular test:

https://github.com/openmm/openmm/blob/master/wrappers/python/openmm/testInstallation.py

Just create an executable Python script called `testInstallation.py` inside the package directory.  Inside it, you can run whatever tests are appropriate for your plugin.

**Comment by lvotapka** [comment]
Yes, but would I need to add anything to the CMakeLists.txt files to discover it? I tried making a test/ directory inside of python/, along with a __init__.py file in hopes that the "make PythonInstall" step would discover it - no dice.

Are you saying that one could just put a testInstallation.py file right inside the openmmexampleplugin/ directory?

**Comment by peastman** [comment]
> Are you saying that one could just put a testInstallation.py file right inside the openmmexampleplugin/ directory?

The `-m` flag just loads an arbitrary module and executes it as a script.  The challenge here is that the Python package for the plugin is entirely generated by SWIG.  If you provide an extra file, you need to modify CMakeLists.txt to copy that file over.

Here's the corresponding script for the main [OpenMM Python package](https://github.com/openmm/openmm/blob/master/wrappers/python/CMakeLists.txt).  It's very complicated because it does a lot: programmatically generate the SWIG definition files based on the C++ source code, copy over a big tree of Python modules and data files, ensure that any change to them will cause the Python package to be reinstalled, etc.  Your version can be much simpler.  Here are the key lines that copy each file.

https://github.com/openmm/openmm/blob/344463118f402cb6b3fc28474c015f56f2d5aff9/wrappers/python/CMakeLists.txt#L85-L91

**Comment by lvotapka** [comment]
Thanks, Peter, I'll give it a shot.
